Repository NCIOCPL/cgov-digital-platform, pull requests merged in 2019-04, with the labels that each got.

#1112 Implement Glossification in WYSIWYG
  docroot/profiles/custom/cgov_site/cgov_site.info.yml
  docroot/profiles/custom/cgov_site/config/install/editor.editor.full_html.yml
  docroot/profiles/custom/cgov_site/config/install/editor.editor.streamlined.yml
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/README.md
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/config/install/rest.resource.pdq_glossary_refresh_api.yml
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/config/install/rest.resource.pdq_glossifier_api.yml
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/css/glossify-dialog.css
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/css/images/caret-down.svg
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/css/images/ex.svg
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/js/plugins/cgov_glossifier/dialogs/glossify.js
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/js/plugins/cgov_glossifier/icons/button.png
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/js/plugins/cgov_glossifier/plugin.js
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/pdq_glossifier.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/pdq_glossifier.install
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/pdq_glossifier.libraries.yml
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/src/Plugin/CKEditorPlugin/CgovGlossifier.php
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/src/Plugin/rest/resource/PDQGlossifierRefresh.php
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/src/Plugin/rest/resource/PDQResource.php
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/tests/src/Functional/ApiTest.php
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/global/Common.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/popups/glossaryPopups.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/popups/popup_functions.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov_admin/cgov_admin.info.yml
Labels: Passed IA Review

#1087 Ticket 967, change date display in video form to checkbox.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_form_display.media.cgov_video.default.yml
Labels: Does Not Pass IA Review

#1321 Embedded Blocks and Embedded Video Carousel
  docroot/profiles/custom/cgov_site/cgov_site.info.yml
  docroot/profiles/custom/cgov_site/config/install/editor.editor.full_html.yml
  docroot/profiles/custom/cgov_site/config/install/editor.editor.streamlined.yml
  docroot/profiles/custom/cgov_site/config/install/filter.format.streamlined.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_content_block/config/install/core.entity_view_display.block_content.raw_html_block.full.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_content_block/config/install/field.storage.block_content.field_youtube_playlist_id.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_embedded_block/README.md
  docroot/profiles/custom/cgov_site/modules/custom/cgov_embedded_block/cgov_embedded_block.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_embedded_block/cgov_embedded_block.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_embedded_block/config/install/embed.button.insert_block_content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_embedded_block/config/install/entity_browser.browser.block_content_browser.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_embedded_block/config/install/views.view.block_content_browser.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_embedded_block/templates/block-content.html.twig
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/cgov_video.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/block_content.type.cgov_video_carousel.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_form_display.block_content.cgov_video_carousel.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.block_content.cgov_video_carousel.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.block_content.cgov_video_carousel.field_youtube_playlist_id.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/language.content_settings.block_content.cgov_video_carousel.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/006_custom_blocks.content.yml
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/global/Common.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/block_content/video_carousel/block-content--cgov-video-carousel--full.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/nciConfig/NCI.config.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/videoCarousel/video-carousel.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov_admin/templates/embeds/video_carousel/block-content--cgov-video-carousel--full.html.twig
Labels: Passed IA Review

#1348 Feature/image carousel
  .gitignore
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Services/CgovNavigationManager.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/cgov_image.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/block_content.type.cgov_image_carousel.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_form_display.block_content.cgov_image_carousel.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_display.block_content.cgov_image_carousel.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_display.media.cgov_contextual_image.image_reference_field_form.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/entity_browser.browser.cgov_image_carousel_image_browser.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/field.field.block_content.cgov_image_carousel.field_carousel_image_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/field.field.block_content.cgov_image_carousel.field_carousel_images.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/field.storage.block_content.field_carousel_image_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/field.storage.block_content.field_carousel_images.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/language.content_settings.block_content.cgov_image_carousel.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/views.view.cgov_image_media_browser.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/tests/src/Kernel/CgovImageFieldStorageTest.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/src/Service/CgovYamlContentEventSubscriber.php
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/global/Common.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/block_content/image_carousel/block-content--cgov-image-carousel--full.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/block_content/image_carousel/field--block-content--field-carousel-images.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/imageCarousel/image-carousel.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_image-video-carousel.scss
  docroot/profiles/custom/cgov_site/themes/custom/cgov_admin/cgov_admin.info.yml
  docroot/profiles/custom/cgov_site/themes/custom/cgov_admin/cgov_admin.libraries.yml
  docroot/profiles/custom/cgov_site/themes/custom/cgov_admin/src/styles/global.css
  docroot/profiles/custom/cgov_site/themes/custom/cgov_admin/templates/embeds/image_carousel/block-content--cgov-image-carousel--full.html.twig
Labels: Passed IA Review

#1365 OTP migration edge case handling.
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/field--field-article-body.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/paragraph--body-section.html.twig
Labels: Passed IA Review

#1368 Add Cgov Schema Exclusion library.
  composer.json
  docroot/lib/CgovPlatform/Tests/CgovSchemaExclusions.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/RolesTest.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/TestKernelTest.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/WorkflowTest.php
  docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/tests/src/Functional/ApiTest.php
  docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/tests/src/Functional/PDQCancerSummaryTest.php
  docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/tests/src/Functional/ApiTest.php
  docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/tests/src/Functional/PDQDrugSummaryTest.php
  docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier/tests/src/Functional/ApiTest.php
  docroot/profiles/custom/cgov_site/tests/src/Functional/CgovSiteTest.php
  docroot/profiles/custom/cgov_site/tests/src/Functional/PdqNodeTypeTest.php
Labels: Technical Item

#1021 Feature/pdq cis
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/core.entity_view_mode.paragraph.otp_toc.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Services/PageOptionsManager.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/pdq_cis_hp_adult_treatment.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/pdq_cis_hp_genetics.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/pdq_cis_hp_iact.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/pdq_cis_hp_ped_treatment.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/pdq_cis_hp_prevention.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/pdq_cis_hp_screening.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/pdq_cis_hp_supportive.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/pdq_cis_patient_adult_treatment.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/pdq_cis_patient_iact.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/pdq_cis_patient_ped_treatment.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/pdq_cis_patient_prevention.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/pdq_cis_patient_screening.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/pdq_cis_patient_supportive.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/pdq_dis.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/core.entity_view_display.node.pdq_cancer_information_summary.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/core.entity_view_display.paragraph.pdq_summary_section.otp_toc.yml
  docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/pdq_cancer_information_summary.module
  docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/src/Plugin/rest/resource/PDQResource.php
  docroot/profiles/custom/cgov_site/modules/custom/pdq_core/config/install/user.role.pdq_importer.yml
  docroot/profiles/custom/cgov_site/modules/custom/pdq_core/src/Plugin/rest/resource/PDQResource.php
  docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/core.entity_view_display.node.pdq_drug_information_summary.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/src/Plugin/rest/resource/PDQResource.php
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/cgov_common.libraries.yml
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/pdq/PDQ.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/pdq/PDQ.scss
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/pageOptions/index.scss
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/pdq/field--otp-toc.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/pdq/node--pdq-cancer-information-summary.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/pdq/node--pdq-drug-information-summary.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/pdq/paragraph--pdq-summary-section--otp-toc.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/pdq/paragraph--pdq-summary-section.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/webpack.entries.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/package-lock.json
  docroot/profiles/custom/cgov_site/themes/custom/cgov/package.json
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_mainContent.scss
Labels: Passed IA Review

#1387 Integrate the cgov_migration module and Site Section migration config.
  composer.json
  composer.lock
  docroot/profiles/custom/cgov_site/cgov_site.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/cgov_migration.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/cgov_migration.install
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.sitesectionsql_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/private-files-mig/sitesectionsql.xml
Labels: Needs Technical Review

#1403 Ticket/1182 embedded infographic
  docroot/profiles/custom/cgov_site/config/install/editor.editor.full_html.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/cgov_infographic.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_view_display.media.cgov_infographic.infographic_display_article_large.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_view_display.media.cgov_infographic.infographic_display_article_medium.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_view_mode.media.infographic_display_article_large.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_view_mode.media.infographic_display_article_medium.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/embed.button.cgov_infographic_button.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/entity_browser.browser.cgov_embedded_infographic_browser.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/views.view.cgov_infographic_media_browser.yml
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/image/image_macros.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/media/infographic/media--cgov-infographic--infographic-display-article-large.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/media/infographic/media--cgov-infographic--infographic-display-article-medium.html.twig
  docroot/profiles/custom/cgov_site/translations/cgov_site.es.po
Labels: Passed IA Review

#1441 Biography tooltip and form updates
  docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/field.field.node.cgov_biography.field_card_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/field.field.node.cgov_biography.field_date_display_mode.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/field.field.node.cgov_biography.field_date_posted.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/field.field.node.cgov_biography.field_date_reviewed.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/field.field.node.cgov_biography.field_feature_card_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/field.field.node.cgov_biography.field_list_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/field.field.node.cgov_biography.field_page_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/field.field.node.cgov_biography.field_pretty_url.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/field.field.node.cgov_biography.field_search_engine_restrictions.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/field.field.node.cgov_biography.field_short_title.yml
Labels: Passed IA Review

#1443 Event tooltip and form updates
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_browser_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_card_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_event_series.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_feature_card_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_image_article.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_image_promotional.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_list_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_page_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_pretty_url.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_search_engine_restrictions.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_short_title.yml
Labels: Passed IA Review

#1477 Update form display for internal/external links
  docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/core.entity_form_display.paragraph.cgov_external_link.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/core.entity_form_display.paragraph.cgov_internal_link.default.yml
Labels: Passed IA Review

#1491 Ticket #1377 - Constrain breadcrumbs to above curr landing page
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/Breadcrumb.php
Labels: Passed IA Review

#1496 Ticket/1314 Video Form Updates and Date Display Bug
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/tests/src/Kernel/CgovImageFieldStorageTest.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_media/cgov_media.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_media/config/install/field.storage.media.field_browser_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_media/config/install/field.storage.media.field_date_posted.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_media/config/install/field.storage.media.field_feature_card_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_media/config/install/field.storage.media.field_list_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_media/config/install/field.storage.media.field_related_resources.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_media/config/install/field.storage.media.field_short_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_media/tests/src/Kernel/CgovMediaFieldStorageTest.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.tokens.inc
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_form_display.media.cgov_video.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_browser_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_card_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_date_display_mode.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_date_posted.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_date_reviewed.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_feature_card_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_list_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_meta_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_pretty_url.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_related_resources.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_search_engine_restrictions.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_short_title.yml
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/media/video/media--cgov-video--full.html.twig
Labels: Passed IA Review

#1500 Feature: Cancer Research Page
  docroot/profiles/custom/cgov_site/cgov_site.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/cgov_cancer_research.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/cgov_cancer_research.install
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/cgov_cancer_research.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.base_field_override.node.cgov_cancer_research.promote.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.base_field_override.node.cgov_cancer_research.status.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.base_field_override.node.cgov_cancer_research.title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_form_display.node.cgov_cancer_research.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_view_display.node.cgov_cancer_research.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_view_display.node.cgov_cancer_research.embedded_feature_card.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_view_display.node.cgov_cancer_research.embedded_feature_card_no_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_view_display.node.cgov_cancer_research.feature_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_view_display.node.cgov_cancer_research.full.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_view_display.node.cgov_cancer_research.teaser.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_view_display.node.cgov_cancer_research.thumbnail_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_view_display.paragraph.cgov_external_link.cancer_research_list_item.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_view_display.paragraph.cgov_internal_link.cancer_research_list_item.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_view_mode.paragraph.cancer_research_list_item.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.field.node.cgov_cancer_research.body.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.field.node.cgov_cancer_research.field_browser_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.field.node.cgov_cancer_research.field_card_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.field.node.cgov_cancer_research.field_date_display_mode.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.field.node.cgov_cancer_research.field_date_posted.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.field.node.cgov_cancer_research.field_date_reviewed.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.field.node.cgov_cancer_research.field_date_updated.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.field.node.cgov_cancer_research.field_feature_card_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.field.node.cgov_cancer_research.field_image_promotional.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.field.node.cgov_cancer_research.field_list_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.field.node.cgov_cancer_research.field_page_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.field.node.cgov_cancer_research.field_pretty_url.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.field.node.cgov_cancer_research.field_search_engine_restrictions.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.field.node.cgov_cancer_research.field_selected_research.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.field.node.cgov_cancer_research.field_short_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.field.node.cgov_cancer_research.field_site_section.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/field.storage.node.field_selected_research.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/language.content_settings.node.cgov_cancer_research.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/node.type.cgov_cancer_research.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/pathauto.pattern.cancer_research_url.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Services/PageOptionsManager.php
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/cancer_research/field--field-display-date.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/cancer_research/field--field-selected-research.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/cancer_research/node--cgov-cancer-research--full.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/listing/paragraph--cgov-external-link--cancer-research-list-item.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/listing/paragraph--cgov-internal-link--cancer-research-list-item.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_managed-lists.scss
Labels: Passed IA Review

#1529 Default admin UI pages to English.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
Labels: Passed IA Review

#1517 Page options issues
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Services/PageOptionsManager.php
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/blogSeries/BlogSeries.scss
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/homelanding/Homelanding.scss
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/block/page_options/block--page-options.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/node--cgov-blog-series--full.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/page--cgov-blog-series.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/home_landing/node--cgov-home-landing--full.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/pdq/node--pdq-drug-information-summary--full.html.twig
Labels: Passed IA Review

#1565 (#1473) Cancer Research Card on CTHPs
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_form_display.node.cgov_cancer_research.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_view_display.node.cgov_cancer_research.cthp_research_card.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_view_display.paragraph.cgov_external_link.cthp_research_card_list_item.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_view_display.paragraph.cgov_internal_link.cthp_research_card_list_item.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_view_mode.node.cthp_research_card.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/core.entity_view_mode.paragraph.cthp_research_card_list_item.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/cgov_cthp.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/core.entity_view_display.paragraph.cgov_cthp_research_card.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/field.field.paragraph.cgov_cthp_research_card.field_cthp_research_page.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/400_breast_cancer_research.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/z040_breast.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/z041_breast-hp.content.yml
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/cgov_common.theme
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/cancer_research/field--field-selected-research--cthp-research-card.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/cancer_research/node--cgov-cancer-research--cthp-research-card.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/listing/paragraph--cgov-external-link--cthp-research-card-list-item.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/listing/paragraph--cgov-internal-link--cthp-research-card-list-item.html.twig
  docroot/profiles/custom/cgov_site/translations/cgov_site.es.po
Labels: Passed IA Review

#1520 Biography page display issues
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/biography/field--field-linkedin-handle.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/biography/field--field-scientific-publications.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/biography/field--field-title.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/biography/field--field-twitter-handle.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/biography/node--cgov-biography--full.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_profile-panel.scss
Labels: Passed IA Review

#1523 (#1174) Public Reuse Text Styling Bugs
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
Labels: Passed IA Review
