Repository NCIOCPL/cgov-digital-platform, pull requests merged in 2019-10, with the labels that each got.

#2464 (#2462) Include the entity alias as a trigger for section cache tag invalidation.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
Labels: Needs Technical Review

#2467 Modify logic to check for all rendering nav roots.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/900_cgov_site_section.content.yml
Labels: Needs IA Review, Needs Technical Review

#2485 (#2484) Fixes for cache tag invalidation when root and display options toggled.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
Labels: Needs Technical Review, Passed IA Review

#2477 Ticket/2347 blog category browser title
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.services.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.tokens.inc
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/metatag.metatag_defaults.node__cgov_blog_series.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/CgovBlogTwigExtensions.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Services/BlogManager.php
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/blog_macros.twig
Labels: Needs Technical Review, Passed IA Review

#2503 (#2493) Include field_levels_to_display as a trigger for cache tag clearing.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
Labels: Passed IA Review, Passed QA

#2504 (#2382) Add ajax callback for updating blog topics related to blog se…
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/field.field.node.cgov_blog_post.field_blog_topics.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Services/BlogManager.php
Labels: Needs Technical Review, Passed IA Review, Passed QA review
