Repository NCIOCPL/cgov-digital-platform, pull requests merged in 2019-09, with the labels that each got.

#2373 (NCIOCPL#2335) The automatic resizing of images can run out of memory.
  composer.json
  composer.lock
  docker/web/Dockerfile
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/cgov_image.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/cgov_image.install
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/system.image.yml
Labels: Passed IA Review

#2297 (#2185) Limit displayed blog categories to only those with blog posts in currrent language.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.services.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Plugin/Block/BlogCategories.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Services/BlogManager.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Services/BlogManagerInterface.php
Labels: Passed IA Review

#2409 Fix click event analytics on CTHP and PDQ pages
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/analytics/AppMeasurement.custom.js
Labels: Passed IA Review

#2418 Analytics loading order issue
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/layout/html.html.twig
Labels: Needs IA Review

#2421 (NCIOCPL#2407) Site Admin Can't Translate Blog Topic.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.install
Labels: Passed IA Review

#2428 (#2426) Cannot preview the first post in a blog series.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Plugin/Block/BlogPager.php
Labels: Does Not Pass IA Review

#2445 (#2383, #2384) Schema.org structured data pilot
  docroot/profiles/custom/cgov_site/cgov_site.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_article/cgov_article.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_article/cgov_article.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/core.entity_form_display.node.cgov_article.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/core.entity_view_display.node.cgov_article.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/core.entity_view_display.node.cgov_article.embedded_feature_card.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/core.entity_view_display.node.cgov_article.embedded_feature_card_no_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/core.entity_view_display.node.cgov_article.feature_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/core.entity_view_display.node.cgov_article.full.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/core.entity_view_display.node.cgov_article.link.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/core.entity_view_display.node.cgov_article.panoramic_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/core.entity_view_display.node.cgov_article.teaser.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/core.entity_view_display.node.cgov_article.thumbnail_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/field.field.node.cgov_article.field_schema_org_data.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_schema_org/cgov_schema_org.features.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_schema_org/cgov_schema_org.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_schema_org/cgov_schema_org.install
  docroot/profiles/custom/cgov_site/modules/custom/cgov_schema_org/cgov_schema_org.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_schema_org/config/install/field.storage.node.field_schema_org_data.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_schema_org/config/schema/cgov_schema_org.schema.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_schema_org/src/Plugin/Field/CgovSchemaOrgEntityFieldItemList.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_schema_org/src/Plugin/Field/FieldFormatter/CgovSchemaOrgEmptyFormatter.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_schema_org/src/Plugin/Field/FieldType/CgovSchemaOrgFieldItem.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_schema_org/src/Plugin/Field/FieldWidget/CgovSchemaOrgWidget.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/012_article-psychological-stress-and-cancer.content.yml
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/cgov_common.theme
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/field--field-article-body.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/paragraph--body-section.html.twig
Labels: Passed IA Review

#2448 (#2315, #2206) - Add CT cache tags, Update Site Section tag logic
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/NavItem.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/SectionNav.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/block/section_nav/block--cgov-section-nav.html.twig
Labels: Needs Technical Review, Passed IA Review

#2458 (#2456) Fix schema.org markup on non-FAQ pages
  docroot/profiles/custom/cgov_site/modules/custom/cgov_article/cgov_article.module
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/cgov_common.theme
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/article/field--field-article-body.html.twig
Labels: Passed IA Review

#2385 [POC] NCIOCPL-000: Prototype for CGov Vocab Manager.
  composer.json
  composer.lock
  docroot/profiles/custom/cgov_site/cgov_site.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_site_section/cgov_site_section.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/cgov_vocab_manager.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/cgov_vocab_manager.links.action.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/cgov_vocab_manager.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/cgov_vocab_manager.routing.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/cgov_vocab_manager.services.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/src/Form/CgovVocabManagerForm.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/src/Manager/CgovVocabManager.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_vocab_manager/src/Routing/RouteSubscriber.php
Labels: Passed IA Review
