Repository NCIOCPL/cgov-digital-platform, pull requests merged in 2019-06, with the labels that each got.

#1893 (NCIOCPL#1878) Fix envrionment variable reference in 'migration://' s…
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/StreamWrapper/CgovMigrationStreamWrapper.php
Labels: Needs Technical Review

#1887 Inline Variant Processing / Bugfixes
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_blogpost_en_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_blogpost_es_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_cancercenter_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_citation_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_contentblock_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_cthpcontentblock_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_event_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_infographic_en_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_infographic_es_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_paragraph_en_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_paragraph_es_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_pressrelease_en_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_pressrelease_es_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/GeneratePlaceholders.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/RemoveRxWrapper.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/ReplaceEmbeds.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/ReplaceLinks.php
  scripts/utility/cgov_migration_load.sh
Labels: Needs Technical Review

#1918 (#1786) Create Application Page content type
  docroot/profiles/custom/cgov_site/cgov_site.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/cgov_application_page.features.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/cgov_application_page.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/cgov_application_page.install
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/cgov_application_page.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.base_field_override.node.cgov_application_page.promote.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.base_field_override.node.cgov_application_page.status.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.base_field_override.node.cgov_application_page.title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_form_display.node.cgov_application_page.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_view_display.node.cgov_application_page.full.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.body.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_browser_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_card_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_date_display_mode.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_date_posted.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_date_reviewed.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_date_updated.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_enable_push_state.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_feature_card_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_image_promotional.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_list_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_meta_tags.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_page_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_pretty_url.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_search_engine_restrictions.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.field.node.cgov_application_page.field_site_section.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/field.storage.node.field_enable_push_state.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/language.content_settings.node.cgov_application_page.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/node.type.cgov_application_page.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/pathauto.pattern.application_page_url.yml
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/application_page/node--cgov-application-page--full.html.twig
Labels: Needs IA Review

#1952 (1921) Replace microsite links. Add additional link attributes.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.contentblock_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_contentblock_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/cross-site-links-dceg.json
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/translationid.json
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/RemoveRxWrapper.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/ReplaceEmbeds.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/ReplaceLinks.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Services/MigrationLogger.php
Labels: Needs Technical Review

#2029 (#2008) Links are not being switched over on microsites.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/CgovPluginBase.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/ReplaceEmbeds.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/ReplaceLinks.php
Labels: Needs ODE

#2043 (#2021, #2019, #2003, #2020) Update error handling, mapping file, link replacement order.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/cgov_migration.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_blogpost_en_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_blogpost_es_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_cancercenter_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_citation_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_contentblock_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_cthpcontentblock_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_event_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_infographic_en_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_infographic_es_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_paragraph_en_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_paragraph_es_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_pressrelease_en_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/config/install/migrate_plus.migration.update_pressrelease_es_migration.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/translationid.json
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/CgovPluginBase.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/ReplaceEmbeds.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/ReplaceInlineImages.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/ReplaceLinks.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Services/MigrationLogger.php
Labels: Passed IA Review

#1929 (#1860, #1857, #1869, #1859, #1870, #1871, #1872, #1873, #2036, #2037, #2038, #2040, #2044) Analytics bugs
  docroot/lib/CgovPlatform/Tests/CgovSchemaExclusions.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/metatag.metatag_defaults.403.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/metatag.metatag_defaults.404.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/000_mobile_menu.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/099_grants_training.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/099_types.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/310_press_archive.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/article.content.yml
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/analytics/analytics.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/page/page--404-en.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/page/page--404-es.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/analytics/AppMeasurement.custom.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/analytics/nci-analytics-functions.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/enlarge/enlarge.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/imageCarousel/image-carousel.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/liveHelpPopup/ProactiveLiveHelp.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/videoCarousel/video-carousel.js
Labels: Needs IA Review

#2073 (#2074) Blog Post pagination issue
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Plugin/Block/BlogPager.php
Labels: Passed IA Review

#2082 (#2055) update data attributes for analytics click functions
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/099_types.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/310_press_archive.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/article.content.yml
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/analytics/analytics.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/analytics/nci-analytics-functions.js
Labels: Analytics

#2093 (#2092) Dynamic Page Title Should Pull Card Title
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/blog_macros.twig
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/blog/node--cgov-blog-series--full.html.twig
Labels: Passed IA Review

#2095 (#2083) Add hook alter to disable Acquia Connector Toolbar
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
Labels: Needs Technical Review
