Repository NCIOCPL/cgov-digital-platform, pull requests merged in 2019-07, with the labels that each got.

#2200 DCEG Launch + DCEG migration data July 11, 2019.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/DCEG/article_en.xml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/DCEG/biocampus.xml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/DCEG/biography.xml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/DCEG/blogpost_en.xml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/DCEG/cgovimage.xml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/DCEG/contentblock.xml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/DCEG/contextualimage.xml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/DCEG/event.xml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/DCEG/eventvenue.xml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/DCEG/externallinksql.xml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/DCEG/file.xml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/DCEG/internallinksql.xml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/DCEG/minilanding_en.xml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/DCEG/para_en.xml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/DCEG/sitesectionsql.xml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/migrations/DCEG/video_en.xml
Labels: Needs Technical Review

#2207 (#2186) embedded entity sizing rules added to print stylesheet
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_print.scss
Labels: Passed IA Review

#2210 (#2209) Secondary feature card styling on homelanding pages
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/green/entrypoints/Green.scss
Labels: Passed IA Review

#2267 Fix sorting for upcoming and past events view.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/views.view.cgov_events.yml
Labels: Passed IA Review

#2270 (#2256) Add 'view latest version' permission to content_previewer role.
  cgov-drupal-users.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install
Labels: Passed IA Review

#2281 (#2277) Metatag fixes
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/metatag.metatag_defaults.node__cgov_blog_series.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/metatag.metatag_defaults.node__cgov_cancer_center.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/metatag.metatag_defaults.node__cgov_cancer_research.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/metatag.metatag_defaults.node__cgov_cthp.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/metatag.metatag_defaults.node__cgov_event.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_home_landing.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_mini_landing.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/config/install/metatag.metatag_defaults.node__cgov_press_release.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/metatag.metatag_defaults.node__cgov_video.yml
  docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/metatag.metatag_defaults.node__pdq_cancer_information_summary.yml
  docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/metatag.metatag_defaults.node__pdq_drug_information_summary.yml
Labels: Needs IA Review, Passed IA Review
