Repository NCIOCPL/cgov-digital-platform, pull requests merged in 2020-07, with the labels that each got.

#2841 (#2833) AP Link font family
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/specialReport/SpecialReport.scss
Labels: Needs QA review, Needs Technical Review, Needs UX Review

#2840 (#2811) Scale hero image without gutters
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/specialReport/SpecialReport.scss
Labels: Needs QA review, Needs Technical Review, Needs UX Review

#2847 (#2780) Content Block for AP Button
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/970_special_report.content.yml
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/assets/sprites/file-pdf-narrow-white-o-thick.svg
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/specialReport/SpecialReport.scss
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/analytics/analytics.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/analytics/nci-analytics-functions.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_special-report-raw.scss
Labels: Needs QA review, Needs Technical Review, Needs UX Review

#2854 (#2582) Special Report Bugfixes
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/specialReport/SpecialReport.scss
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_special-report-raw.scss
Labels: Needs QA review, Needs Technical Review, Needs UX Review

#2832 (#2648) Configure fast 404.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/EventSubscriber/ResponseCacheSubscriber.php
  docroot/sites/settings/cgov_fast_404.settings.php
Labels: Passed UX Review

#2860 (#2859) Fix for config / features dependency issues
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_mini_landing.field_landing_contents.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/cgov_image.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/cgov_image.install
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_form_display.media.cgov_contextual_image.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_form_display.media.cgov_image.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_display.block_content.cgov_image_carousel.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_display.media.cgov_contextual_image.image_reference_field_form.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_display.media.cgov_image.image_reference_field_form.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_mode.node.borderless_card_image.yml
Labels: Needs QA review, Needs Technical Review

#2856 (#2851) Update glossary app package to v1.0.3
  docroot/profiles/custom/cgov_site/themes/custom/cgov/local_packages/glossary-app-1.0.1-npm.tgz
  docroot/profiles/custom/cgov_site/themes/custom/cgov/local_packages/glossary-app-1.0.3-npm.tgz
  docroot/profiles/custom/cgov_site/themes/custom/cgov/package-lock.json
  docroot/profiles/custom/cgov_site/themes/custom/cgov/package.json
Labels: Passed QA review, Passed UX Review

#2866 (#2865) Fix for invalid markup within the landing page node template.
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/content/home_landing/node--cgov-home-landing--full.html.twig
Labels: Needs QA review, Needs Technical Review, Needs UX Review
