Repository NCIOCPL/cgov-digital-platform, pull requests merged in 2020-03, with the labels that each got.

#2652 (#2644) Turn minification back on.
  docroot/profiles/custom/cgov_site/themes/custom/cgov/package-lock.json
  docroot/profiles/custom/cgov_site/themes/custom/cgov/package.json
  docroot/profiles/custom/cgov_site/themes/custom/cgov/webpack.base.config.js
Labels: Passed QA review

#2638 (#2466) Add the cgov_mail module.
  docroot/profiles/custom/cgov_site/cgov_site.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/cgov_mail.features.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/cgov_mail.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/cgov_mail.menu.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/cgov_mail.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/cgov_mail.routing.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/config/install/cgov_mail.settings.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/config/schema/cgov_mail.schema.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/src/Controller/MailAPIController.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/src/Form/MailSettingsForm.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/src/Plugin/Mail/CgovMailLogger.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/email-form.content.yml
  docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_errorPage.scss
  docroot/sites/settings/cgov_core.settings.php
Labels: Needs Technical Review, Passed QA review, Passed UX Review

#2658 (#2657) Remove features from cgov_mail.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_mail/cgov_mail.features.yml
Labels: Needs Technical Review, WIP

#2650 (#2628) Purple theme infographic button
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/variants/purple/entrypoints/Purple.scss
Labels: Passed UX Review

#2699 (#2698) Update Spanish logo for nci-connect.
  docroot/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/logos/ccr-logo-full-es.svg
Labels: Needs UX Review
