Repository NCIOCPL/cgov-digital-platform, pull requests merged in 2022-11, with the labels that each got.

#3600 (#3396) Updating the modules - embed (1.4.0 to 1.60) & entity_browser…
  composer.json
  composer.lock
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Plugin/Block/BlogPager.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/Block/PageOptions.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/cgov_home_landing.services.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/src/CgovHomeLandingPageTwigExtension.php
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/cards/paragraph--cgov-card-borderless.html.twig
Labels: Passed QA review

#3618 (#3387) Remove Legacy from NCIDS
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/000_ncids_trans_legacy_blocks.content.yml
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/global/Common.js
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/global/Common.scss
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/webpack.entries.js
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/ncids_trans.info.yml
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/ncids_trans.libraries.yml
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block/legacy/breadcrumb/block--ncids-trans-legacy-breadcrumb.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block/legacy/main_nav/block--cgov-main-nav.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block/legacy/page_options/block--cgov-common-languagebar.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block/legacy/page_options/block--page-options.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block/legacy/section_nav/block--cgov-section-nav.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/layout/html.html.twig
Labels: Passed QA review, Redesign PR

#3569 (#3279) Autosuggest Setup
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.autocomplete.test.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.autosuggest.dom.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.without-search.dom.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/_nci-header.scss
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/auto-suggest-analytics-handlers.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-autocomplete/__tests__/cgdp-autocomplete-adaptor.test.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-autocomplete/__tests__/data/autosuggest-searchText-can.json
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-autocomplete/cgdp-autocomplete-adapter.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-autocomplete/index.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/nci-header.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block/ncids/block--ncids-header.html.twig
Labels: Redesign PR
