Repository NCIOCPL/cgov-digital-platform, pull requests merged in 2023-07, with the labels that each got.

#3932 (#3674) Mobile Menu Fix
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mobile-menu/__tests__/cgdp-mobile-menu-adaptor.test.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mobile-menu/__tests__/data/section-nav/844114.json
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mobile-menu/cgdp-mobile-menu-adaptor.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/nci-header.ts
Labels: Passed QA review, Redesign PR

#3935 (#3934) Remove lazy loading from NCIDS Hero
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.paragraph.ncids_hero.default.yml
Labels: Passed QA review

#3963 (#3907) Resolved RSS feed image length issue
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTwigExtensions.php
Labels: Passed QA review

#3948 (#3637) Build NCIDS Feature Card Multimedia
  docroot/profiles/custom/cgov_site/modules/custom/cgov_file/config/install/core.entity_view_display.media.cgov_file.ncids_feature_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.paragraph.ncids_3_feature_card_row.field_row_cards.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_image/config/install/core.entity_view_mode.media.ncids_feature_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/core.entity_view_display.media.cgov_infographic.ncids_feature_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/cgov_promo.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/core.entity_form_display.paragraph.ncids_feature_card_multimedia.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/core.entity_view_display.paragraph.ncids_feature_card_multimedia.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.ncids_feature_card_multimedia.field_featured_media.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.ncids_feature_card_multimedia.field_override_card_description.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.ncids_feature_card_multimedia.field_override_card_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.field.paragraph.ncids_feature_card_multimedia.field_override_image_promotional.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/field.storage.paragraph.field_featured_media.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_promo/config/install/paragraphs.paragraphs_type.ncids_feature_card_multimedia.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/993_ncids_feature_card_multimedia_test_page.content.yml
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/cgdp-feature-card-row/__tests__/cgdp-feature-card.test.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/cards/media--ncids-feature-card-image.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/cards/paragraph--ncids-feature-card-multimedia.html.twig
Labels: Redesign PR

#3969 (#3962) Promo Block Production Error Fix
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
Labels: Passed QA review
