Repository NCIOCPL/cgov-digital-platform, pull requests merged in 2024-03, with the labels that each got.

#4256 (#3695, #4255) Replace Behat with Cypress
  .github/workflows/ci.yml
  blt/blt.yml
  blt/ci.blt.yml
  blt/src/Blt/Plugin/Commands/Tests/CypressTestCommand.php
  blt/src/Blt/Plugin/Commands/XvfbCommands.php
  blt/src/CgovNpmTrait.php
  blt/src/Task/Npm/CleanInstall.php
  blt/src/Task/Npm/RunScript.php
  docker/web/Dockerfile
  phpcs.xml
  tests/cypress/.gitignore
  tests/cypress/cypress.config.js
  tests/cypress/cypress/e2e/common/index.js
  tests/cypress/cypress/e2e/pretest/BasicSetup.feature
  tests/cypress/cypress/e2e/pretest/README.md
  tests/cypress/cypress/e2e/pretest/parallel-weights.json
  tests/cypress/cypress/e2e/tests/BehatParallel/EditorialWorkflowMedia.feature
  tests/cypress/cypress/e2e/tests/BehatParallel/EditorialWorkflowNodes.feature
  tests/cypress/cypress/e2e/tests/BehatParallel/PDQ.feature
  tests/cypress/cypress/e2e/tests/BehatParallel/SimpleWorkflowBlocks.feature
  tests/cypress/cypress/e2e/tests/BehatParallel/SimpleWorkflowMedia.feature
  tests/cypress/cypress/e2e/tests/ContentCreationParallel/ApplicationPage.feature
  tests/cypress/cypress/e2e/tests/ContentCreationParallel/Article.feature
  tests/cypress/cypress/e2e/tests/ContentCreationParallel/Biography.feature
  tests/cypress/cypress/e2e/tests/ContentCreationParallel/BlogPost.feature
  tests/cypress/cypress/e2e/tests/ContentCreationParallel/BlogSeries.feature
  tests/cypress/cypress/e2e/tests/ContentCreationParallel/CancerCenter.feature
  tests/cypress/cypress/e2e/tests/ContentCreationParallel/CancerResearch.feature
  tests/cypress/cypress/e2e/tests/ContentCreationParallel/Event.feature
  tests/cypress/cypress/e2e/tests/ContentCreationParallel/HomeLanding.feature
  tests/cypress/cypress/e2e/tests/ContentCreationParallel/MiniLanding.feature
  tests/cypress/cypress/e2e/tests/ContentCreationParallel/PressRelease.feature
  tests/cypress/cypress/e2e/tests/parallel-weights.json
  tests/cypress/cypress/fixtures/example.json
  tests/cypress/cypress/plugins/index.js
  tests/cypress/cypress/support/commands.js
  tests/cypress/cypress/support/e2e.js
  tests/cypress/multi-reporter-config.json
  tests/cypress/package-lock.json
  tests/cypress/package.json
Labels: Needs Technical Review

#4272 (#3446) Update and Restore Grants & Contracts Chart
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/601_factbook_pages.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/data_files/factbook-grants-contracts.json
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/Chart.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/chart.scss
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/index.js
  docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/grants-contracts.js
Labels: Needs Technical Review, Passed QA review

#4263 (#4236) Add additional library to home and landing page
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/field.storage.node.field_additional_library.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/cgov_home_landing.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_form_display.node.cgov_home_landing.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.borderless_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.embedded_feature_card.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.embedded_feature_card_no_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.feature_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.full.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.link.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.ncids_feature_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.ncids_promo_block_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.panoramic_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.teaser.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/core.entity_view_display.node.cgov_home_landing.thumbnail_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/field.field.node.cgov_home_landing.field_additional_library.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_addl_library.content.yml
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-lib-test/addl-lib-test.scss
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/addl-lib-test/addl-lib-test.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/webpack.entries.js
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/ncids_trans.libraries.yml
Labels: Passed QA review

#4287 (#4245) Reorder reviewed and updated date checkboxes
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/core.entity_form_display.node.cgov_application_page.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/field.storage.media.field_date_display_mode.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/field.storage.node.field_date_display_mode.yml
Labels: Passed QA review

#4278 (#4233) Allow site name in meta title
  docroot/profiles/custom/cgov_site/cgov_site.install
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/cgov_application_page.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/metatag.metatag_defaults.node__cgov_application_page.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/metatag.metatag_defaults.node__cgov_article.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/metatag.metatag_defaults.node__cgov_biography.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/metatag.metatag_defaults.node__cgov_blog_post.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/metatag.metatag_defaults.node__cgov_blog_series.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/metatag.metatag_defaults.node__cgov_cancer_center.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/metatag.metatag_defaults.node__cgov_cancer_research.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.links.menu.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.routing.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/metatag.metatag_defaults.403.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/metatag.metatag_defaults.404.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/metatag.metatag_defaults.global.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/metatag.metatag_defaults.media.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/metatag.metatag_defaults.node.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/sitebranding.settings.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/schema/cgov_core.schema.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTools.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Form/SiteBrandingSettingsForm.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/metatag.metatag_defaults.node__cgov_cthp.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/metatag.metatag_defaults.node__cgov_event.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_home_landing.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_mini_landing.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/metatag.metatag_defaults.media__cgov_infographic.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc
  docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/config/install/metatag.metatag_defaults.node__cgov_press_release.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/metatag.metatag_defaults.media__cgov_video.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/metatag.metatag_defaults.node__cgov_video.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_adult_metastatic_tumor_manual_trial_listing_page.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_cam_manual_trial_listing_page.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_chicken_pox_manual_trial_listing_page.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_covid19_manual_trial_listing_page.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_cts.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_disease_dynamic_trial_listing_page.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_drug_dictionary.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_glossary_genetics.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_glossary_terms.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_intervention_dynamic_trial_listing_page.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_js_app_module.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_kidney_cancer_manual_trial_listing_page.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_sitewide_search_dceg.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_sitewide_search_nciconnect.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/009_app_module_sitewide_search_nciconnect_spanish.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/z100_app_module_sitewide_search_cgov.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/z100_app_module_sitewide_search_cgov_spanish.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/metatag.metatag_defaults.node__pdq_cancer_information_summary.yml
  docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/metatag.metatag_defaults.node__pdq_drug_information_summary.yml
Labels: Passed UX Review, Needs Technical Review, Passed QA review
