Repository NCIOCPL/cgov-digital-platform, pull requests merged in 2024-04, with the labels that each got.

#4297 (#4262) Enabling Admin user if its blocked.
  drush/Commands/cgov/CgovUserCommands.php
Labels: Needs QA review

#4298 (#4268) Update to newest version of NCIDS
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/000_ncids_trans_blocks.content.yml
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/package-lock.json
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/package.json
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/ncids-home-landing/ncids-home-landing.scss
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.autosuggest.dom.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.mega-menu-basepath.dom.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.mega-menu.dom.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/__tests__/nci-header.without-search.dom.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-autocomplete/__tests__/cgdp-autocomplete-adaptor.test.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-autocomplete/cgdp-autocomplete-adapter.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mega-menu/__tests__/cgdp-megamenu-adapter.test.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mega-menu/cgdp-megamenu-adapter.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mobile-menu/__tests__/cgdp-mobile-menu-adapter.test.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mobile-menu/cgdp-mobile-menu-adapter.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/cgdp-mobile-menu/index.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/nci-header/nci-header.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/__tests__/usa-footer.dom.mock.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-footer/usa-footer.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-sidenav/__tests__/usa-sidenav.dom.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-sidenav/__tests__/usa-sidenav.test.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/lib/components/usa-site-alert/usa-site-alert.ts
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block/ncids/block--ncids-header.html.twig
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/templates/block/ncids/block--ncids-sidenav.html.twig
Labels: Needs UX Review

#4301 (#2884) Spanish OG:Image is incorrectly pulling English image
  docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc
Labels: Passed QA review

#4290 (#2260) Add Override Thumbnail Image to Videos
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/cgov_video.features.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/cgov_video.info.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/cgov_video.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_form_display.media.cgov_video.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.entity_browser_selected_entity.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.full.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.image_reference_field_form.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.link.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.multimedia_card.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.thumbnail_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_cthp_multimedia.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_large_no_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_large_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_medium_no_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_medium_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_ncids_inline.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_small_no_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/core.entity_view_display.media.cgov_video.video_display_small_title.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_override_thumbnail_video.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.storage.media.field_override_thumbnail_video.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/image.style.video_display_cthp_card.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/image.style.video_display_large.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/image.style.video_display_medium.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/image.style.video_display_ncids_inline.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/image.style.video_display_small.yml
Labels: Needs Technical Review, Passed QA review

#4307 (#4247) Remove og:sitename metatag from drupal output
  docroot/profiles/custom/cgov_site/modules/custom/cgov_application_page/config/install/metatag.metatag_defaults.node__cgov_application_page.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_article/config/install/metatag.metatag_defaults.node__cgov_article.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_biography/config/install/metatag.metatag_defaults.node__cgov_biography.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/metatag.metatag_defaults.node__cgov_blog_post.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/config/install/metatag.metatag_defaults.node__cgov_blog_series.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_center/config/install/metatag.metatag_defaults.node__cgov_cancer_center.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cancer_research/config/install/metatag.metatag_defaults.node__cgov_cancer_research.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/metatag.metatag_defaults.global.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_cthp/config/install/metatag.metatag_defaults.node__cgov_cthp.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/metatag.metatag_defaults.node__cgov_event.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_home_landing.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_home_landing/config/install/metatag.metatag_defaults.node__cgov_mini_landing.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_infographic/config/install/metatag.metatag_defaults.media__cgov_infographic.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc
  docroot/profiles/custom/cgov_site/modules/custom/cgov_press_release/config/install/metatag.metatag_defaults.node__cgov_press_release.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/metatag.metatag_defaults.media__cgov_video.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/metatag.metatag_defaults.node__cgov_video.yml
  docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/config/install/metatag.metatag_defaults.node__pdq_cancer_information_summary.yml
  docroot/profiles/custom/cgov_site/modules/custom/pdq_drug_information_summary/config/install/metatag.metatag_defaults.node__pdq_drug_information_summary.yml
Labels: Passed QA review

#4325 (#4326) Fix for spanish override thumbnail video field.
  docroot/profiles/custom/cgov_site/modules/custom/cgov_video/config/install/field.field.media.cgov_video.field_override_thumbnail_video.yml
Labels: Passed QA review
