Repository NCIOCPL/cgov-digital-platform, pull requests merged in 2025-06, with the labels that each got.

#4770 (#4733) Updates Blog Post Lists
  docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end/src/entrypoints/blogs/blogs-legacy.scss
Labels: Passed UX Review, Needs Technical Review, Passed QA review

#4764 (#4757) Update Events Dynamic List for MLPS Structure
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/metatag/Tag/CgdpEventGroup.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Plugin/metatag/Tag/CgdpEventSeries.php
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/cgov_event.install
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_form_display.node.cgov_event.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.borderless_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.default.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.embedded_feature_card.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.embedded_feature_card_no_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.event_list_item.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.event_ncids_collection_condensed.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.feature_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.full.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.ncids_feature_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.ncids_flag_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.ncids_list_item_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.ncids_promo_block_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.teaser.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/core.entity_view_display.node.cgov_event.thumbnail_card_image.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.field.node.cgov_event.field_event_group.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/field.storage.node.field_event_group.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/language.content_settings.taxonomy_term.cgov_event_group.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/metatag.metatag_defaults.node__cgov_event.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/taxonomy.vocabulary.cgov_event_group.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_event/config/install/views.view.cgov_events.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/250_events_views.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/500_event_test.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/999_ncids-mini-landing-dynamic-list-events.content.yml
  docroot/profiles/custom/cgov_site/modules/custom/cgov_yaml_content/content/event-i-score-workshop.content.yml
Labels: Passed QA review

#4779 (#4773) Change text format for Intro Text on Article Pages
  docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.install
Labels: Needs Technical Review, Passed QA review
